name: test_pipeline
on: [push]

# Bloqueia o main de receber commits diretos e força PR
# Colocar Validacoes no BASH -> Terraform

env:

  FOLDER_NAME: '.'
  RESOURCE_GROUP: "dumbapp-sampl_group"
  ARM_ACCESS_KEY: ${{secrets.ARM_ACCESS_KEY}}
#  APP_NAME: 'dumbapp-sample'
#  SKU_TYPE: 'F1'
#  REGION: 'westeurope'
#  PYTHON_VERSION: '3.9'
  
jobs: 
  teste:
    runs-on: ubuntu-20.04
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: azure login
        uses: azure/login@v1
        with: 
          creds: '${{secrets.azure_credentials}}'
      - name: pip install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: HashiCorp - Setup Terraform      
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        working-directory: './terraform'
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: './terraform'
        run: |
          terraform plan    
        env:
          TF_VAR_PYTHON_VERSION: ${{vars.PYTHON_VERSION}}
          TF_VAR_SKU_TYPE: ${{vars.SKU_TYPE}}
          TF_VAR_REGION: ${{vars.REGION}}
          TF_VAR_APP_NAME: ${{vars.APP_NAME}}

      - name: Terraform Apply
        working-directory: './terraform'
        run: |
          terraform apply -auto-approve
        env:
          TF_VAR_PYTHON_VERSION: ${{vars.PYTHON_VERSION}}
          TF_VAR_SKU_TYPE: ${{vars.SKU_TYPE}}
          TF_VAR_REGION: ${{vars.REGION}}
          TF_VAR_APP_NAME: ${{vars.APP_NAME}}

      - name: deploy webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.APP_NAME}}
          package: ${{env.FOLDER_NAME}}
          startup-command: 'python manage.py runserver'
          resource-group-name: ${{env.RESOURCE_GROUP}}
      

